/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as MosquesRouteImport } from './routes/mosques'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMosqueAdminRouteImport } from './routes/_authenticated/mosque-admin'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquesRoute = MosquesRouteImport.update({
  id: '/mosques',
  path: '/mosques',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMosqueAdminRoute =
  AuthenticatedMosqueAdminRouteImport.update({
    id: '/mosque-admin',
    path: '/mosque-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/events': typeof EventsRoute
  '/hadith': typeof HadithRoute
  '/live': typeof LiveRoute
  '/mosques': typeof MosquesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/tasbih': typeof TasbihRoute
  '/mosque-admin': typeof AuthenticatedMosqueAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/events': typeof EventsRoute
  '/hadith': typeof HadithRoute
  '/live': typeof LiveRoute
  '/mosques': typeof MosquesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/tasbih': typeof TasbihRoute
  '/mosque-admin': typeof AuthenticatedMosqueAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/events': typeof EventsRoute
  '/hadith': typeof HadithRoute
  '/live': typeof LiveRoute
  '/mosques': typeof MosquesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/tasbih': typeof TasbihRoute
  '/_authenticated/mosque-admin': typeof AuthenticatedMosqueAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/events'
    | '/hadith'
    | '/live'
    | '/mosques'
    | '/prayer-times'
    | '/profile'
    | '/qibla'
    | '/quran'
    | '/tasbih'
    | '/mosque-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/events'
    | '/hadith'
    | '/live'
    | '/mosques'
    | '/prayer-times'
    | '/profile'
    | '/qibla'
    | '/quran'
    | '/tasbih'
    | '/mosque-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/announcements'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/events'
    | '/hadith'
    | '/live'
    | '/mosques'
    | '/prayer-times'
    | '/profile'
    | '/qibla'
    | '/quran'
    | '/tasbih'
    | '/_authenticated/mosque-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DuasRoute: typeof DuasRoute
  EventsRoute: typeof EventsRoute
  HadithRoute: typeof HadithRoute
  LiveRoute: typeof LiveRoute
  MosquesRoute: typeof MosquesRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  ProfileRoute: typeof ProfileRoute
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRoute
  TasbihRoute: typeof TasbihRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosques': {
      id: '/mosques'
      path: '/mosques'
      fullPath: '/mosques'
      preLoaderRoute: typeof MosquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mosque-admin': {
      id: '/_authenticated/mosque-admin'
      path: '/mosque-admin'
      fullPath: '/mosque-admin'
      preLoaderRoute: typeof AuthenticatedMosqueAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMosqueAdminRoute: typeof AuthenticatedMosqueAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMosqueAdminRoute: AuthenticatedMosqueAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DuasRoute: DuasRoute,
  EventsRoute: EventsRoute,
  HadithRoute: HadithRoute,
  LiveRoute: LiveRoute,
  MosquesRoute: MosquesRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  ProfileRoute: ProfileRoute,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRoute,
  TasbihRoute: TasbihRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
